WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Python_projects\Urban_homework\tests_12_4.py", line 73, in test_run
    obj2 = Runner(['aaa', 3])
           ^^^^^^^^^^^^^^^^^^
  File "D:\Python_projects\Urban_homework\tests_12_4.py", line 12, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано list
WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Python_projects\Urban_homework\tests_12_4.py", line 60, in test_walk
    obj = Runner('walk', speed=-3)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python_projects\Urban_homework\tests_12_4.py", line 17, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -3
